version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5433
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=B10Pr0t!3645
      - POSTGRES_USER=bioprot
      - POSTGRES_DB=bioprotNext
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db
