version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: B10Pr0t!3645
      POSTGRES_DB: bioprotNext
    ports:
      - 5433:5433
