version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=j43bfv34jv34bidb4ihd34vrf4f3
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db
